### ISSUE TITLE
Mistakes indication

### ISSUE THREAD

**Issue by AlexKlo** [FadeevEgor/PracticeTurkish#1]
After received my mistakes to Telegram, I wanted to practice writing sentences. 
It works, but I made a lot of grammatical mistakes due to my illiteracy.
It will be cool if the Bot underlines the mistakes and sends the correct version, as Google Translete does. 

![image](https://user-images.githubusercontent.com/65765845/227448842-2b79e009-056f-4fc6-bd2a-9ece4f4fa73e.png)

**Comment by FadeevEgor** [comment]
The issue is not related to the project. 

See [PracticeTurkishBot](https://github.com/FadeevEgor/PracticeTurkishBot) repository.
